# Generated by Django 4.1 on 2023-02-20 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_log'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='task',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.task'),
        ),
    ]
