# Generated by Django 4.1 on 2023-09-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_create_time_report_report_path_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_path_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_path_en',
            field=models.TextField(null=True),
        ),
    ]
