# Generated by Django 4.1 on 2022-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_index', models.CharField(blank=True, default='', max_length=1024)),
                ('library_number', models.CharField(blank=True, default='', max_length=1024)),
                ('reagent_box', models.CharField(max_length=128)),
                ('nucleic_break_type', models.CharField(max_length=128)),
                ('library_input', models.CharField(max_length=128)),
                ('index_type', models.CharField(blank=True, default='', max_length=1024)),
                ('index_number', models.CharField(blank=True, default='', max_length=1024)),
                ('hybrid_input', models.CharField(blank=True, default='', max_length=1024)),
                ('risk', models.BooleanField()),
                ('nucleic_level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4)),
                ('sample_meta_id', models.BigIntegerField(default=-1)),
                ('sample_identifier', models.CharField(max_length=256)),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('company', models.CharField(max_length=1024)),
                ('nucleic_type', models.CharField(choices=[('gDNA', 'gDNA'), ('cfDNA', 'cfDNA'), ('RNA', 'RNA')], max_length=16)),
                ('fastq1_path', models.CharField(max_length=1024)),
                ('fastq2_path', models.CharField(max_length=1024)),
                ('user_id', models.BigIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '样本数据',
                'verbose_name_plural': '样本数据',
                'db_table': 'samples',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='SampleMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('test_date', models.DateField()),
                ('sample_componet', models.CharField(max_length=128)),
                ('sample_type', models.CharField(max_length=128)),
                ('panel_proportion', models.FloatField(default=0.0)),
                ('is_panel', models.BooleanField(default=False)),
                ('user_id', models.BigIntegerField(default=1)),
                ('patient_id', models.BigIntegerField(default=1)),
                ('patient_identifier', models.CharField(max_length=256)),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '样本',
                'verbose_name_plural': '样本',
                'db_table': 'sample_meta',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
    ]
