# Generated by Django 4.1 on 2022-09-01 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0))),
                ('project_index', models.CharField(blank=True, default='', max_length=1024)),
                ('platform', models.CharField(blank=True, default='', max_length=1024)),
                ('company', models.CharField(blank=True, default='', max_length=1024)),
                ('test_type', models.CharField(blank=True, default='', max_length=1024)),
                ('index_type', models.CharField(default='', max_length=1024)),
                ('origin_sample_info', models.CharField(default='', max_length=1024)),
                ('sample_orginization', models.CharField(blank=True, default='', max_length=1024)),
                ('sample_type', models.CharField(default='', max_length=1024)),
                ('library_type', models.CharField(default='', max_length=256)),
                ('prob_content', models.CharField(default='', max_length=1024)),
                ('pooling_library', models.CharField(default='', max_length=256)),
                ('index_number', models.CharField(default='', max_length=1024)),
                ('barocode_1', models.CharField(blank=True, default='', max_length=1024)),
                ('barocode_2', models.CharField(blank=True, default='', max_length=1024)),
                ('sequence_size', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
                ('real_size', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
                ('quality_30', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
                ('analysis_type', models.CharField(blank=True, default='', max_length=1024)),
                ('building_library_type', models.CharField(blank=True, default='', max_length=1024)),
                ('break_type', models.CharField(blank=True, default='', max_length=1024)),
                ('circle_numbers', models.IntegerField(default=0)),
                ('fastq1_path', models.CharField(blank=True, default='', max_length=1024)),
                ('fastq2_path', models.CharField(blank=True, default='', max_length=1024)),
                ('bam1_path', models.CharField(blank=True, default='', max_length=1024)),
                ('bam1_tool', models.CharField(blank=True, default='', max_length=1024)),
                ('bam2_path', models.CharField(blank=True, default='', max_length=1024)),
                ('bam2_tool', models.CharField(blank=True, default='', max_length=1024)),
                ('bam_location', models.CharField(default='', max_length=1024)),
                ('task_id', models.BigIntegerField(null=True)),
                ('result_path', models.CharField(max_length=1024, null=True)),
                ('user_id', models.BigIntegerField(default=1)),
                ('standard_code', models.CharField(blank=True, default='', max_length=1024)),
                ('backup1', models.CharField(blank=True, default='', max_length=128)),
                ('backup2', models.CharField(blank=True, default='', max_length=128)),
                ('backup3', models.CharField(blank=True, default='', max_length=128)),
                ('backup4', models.CharField(blank=True, default='', max_length=128)),
                ('backup5', models.CharField(blank=True, default='', max_length=128)),
                ('backup6', models.CharField(blank=True, default='', max_length=128)),
                ('backup7', models.CharField(blank=True, default='', max_length=128)),
                ('backup8', models.CharField(blank=True, default='', max_length=128)),
                ('backup9', models.CharField(blank=True, default='', max_length=128)),
                ('backup10', models.CharField(blank=True, default='', max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '样本',
                'verbose_name_plural': '样本',
                'db_table': 'sample',
                'ordering': ['-id'],
                'get_latest_by': 'id',
                'unique_together': {('test_date', 'library_type', 'pooling_library')},
            },
        ),
    ]
