# Generated by Django 2.1 on 2020-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('desp', models.TextField()),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, max_length=64)),
                ('reagent', models.CharField(blank=True, max_length=64)),
                ('reagent_type', models.CharField(blank=True, max_length=64)),
                ('reagent_version', models.CharField(blank=True, max_length=64)),
                ('index_type', models.CharField(max_length=64)),
                ('origin_sample_info', models.CharField(max_length=256)),
                ('sample_organization', models.CharField(max_length=256)),
                ('sample_type', models.CharField(max_length=64)),
                ('library_type', models.CharField(max_length=64)),
                ('prob_content', models.CharField(max_length=64)),
                ('hybridization_library', models.CharField(max_length=64)),
                ('pooling_library', models.CharField(max_length=64)),
                ('index_number', models.CharField(max_length=64)),
                ('index_i7', models.CharField(max_length=64)),
                ('index_i5_nova', models.CharField(max_length=64)),
                ('index_i5_next', models.CharField(max_length=64)),
                ('barocode_1', models.CharField(max_length=64)),
                ('barocode_2', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=256)),
                ('bam_location', models.TextField()),
                ('sequence_size', models.IntegerField(default=-1)),
                ('real_size', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sample',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
    ]
