# Generated by Django 4.1 on 2022-09-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemeta',
            name='project_index',
        ),
    ]
