# Generated by Django 2.1 on 2020-10-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'get_latest_by': 'id', 'ordering': ['-id'], 'verbose_name': '样本', 'verbose_name_plural': '样本'},
        ),
    ]
