# Generated by Django 4.1 on 2023-02-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_parent'),
        ('sample', '0002_remove_sample_sample_meta_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='samplemeta',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='samplemeta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
