# Generated by Django 2.1 on 2020-11-11 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20201027_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='reagent',
            new_name='test_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='desp',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='hybridization_library',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='index_i5_next',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='index_i5_nova',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='index_i7',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='reagent_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='reagent_version',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_organization',
        ),
        migrations.AddField(
            model_name='sample',
            name='project_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sample',
            name='project_index',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sample',
            name='quality_30',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_orginization',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_date',
            field=models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_organizer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bam_location',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='barocode_1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='barocode_2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_number',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='origin_sample_info',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='pooling_library',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='prob_content',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
