# Generated by Django 4.1 on 2022-09-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_remove_samplemeta_project_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='nucleic_break_type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
