# Generated by Django 4.1 on 2023-09-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_remove_sample_user_id_remove_samplemeta_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='fastq2_path',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
    ]
