# Generated by Django 2.1 on 2020-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20201112_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
