# Generated by Django 2.1 on 2020-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20201112_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='project_code',
            new_name='analysis_type',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='test_organizer',
            new_name='break_type',
        ),
        migrations.AddField(
            model_name='sample',
            name='bam1_path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sample',
            name='bam1_tool',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sample',
            name='bam2_path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sample',
            name='bam2_tool',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sample',
            name='building_library_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sample',
            name='circle_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='fastq1_path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sample',
            name='fastq2_path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
