# Generated by Django 2.1 on 2020-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20201114_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='location',
        ),
    ]
