# Generated by Django 2.1 on 2020-11-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_remove_sample_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('test_date', 'library_type', 'pooling_library')},
        ),
    ]
