# Generated by Django 2.1 on 2020-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20201114_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='task_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
