# Generated by Django 2.1 on 2020-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_sample_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='user_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
