# Generated by Django 2.1 on 2020-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_sample_result_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='standard_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
