# Generated by Django 2.1 on 2020-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_sample_standard_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='backup1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup10',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup3',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup4',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup5',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup6',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup7',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup8',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='backup9',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
