# Generated by Django 2.1 on 2021-01-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_auto_20201209_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='analysis_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='barocode_1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='barocode_2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='break_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='building_library_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='company',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='pooling_library',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='prob_content',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project_index',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_orginization',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='test_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
