# Generated by Django 2.1 on 2021-08-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_auto_20210115_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='analysis_type',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bam1_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bam1_tool',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bam2_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bam2_tool',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bam_location',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='barocode_1',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='barocode_2',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='break_type',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='building_library_type',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='company',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='fastq1_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='fastq2_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_number',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_type',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='origin_sample_info',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='prob_content',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project_index',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='result_path',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_orginization',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='standard_code',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sample',
            name='test_type',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
