# Generated by Django 4.1 on 2022-09-01 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('caption', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'http动作表',
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='url标题')),
                ('url', models.CharField(max_length=32, verbose_name='含正则的url')),
                ('alias', models.CharField(max_length=32, null=True, verbose_name='url别名')),
            ],
            options={
                'verbose_name_plural': 'url表',
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Permission2Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.TextField(blank=True, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('customer_func', models.CharField(blank=True, max_length=32, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.action')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permission2action')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.permission')),
            ],
            options={
                'verbose_name_plural': '权限表',
                'db_table': 'permission2action',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='角色名')),
                ('permission2action', models.ManyToManyField(to='rbac.permission2action')),
            ],
            options={
                'verbose_name_plural': '角色表',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User2Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2role', to='account.account')),
            ],
            options={
                'verbose_name_plural': '用户角色表',
                'db_table': 'user2role',
            },
        ),
    ]
