# Generated by Django 3.2.3 on 2022-08-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220813_0837'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2role', to='account.account'),
        ),
    ]
