# Generated by Django 2.1 on 2020-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
