# Generated by Django 4.1 on 2024-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230525_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='disk_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
