# Generated by Django 3.2.3 on 2022-09-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220813_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='disk_limit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='used_disk',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
