# Generated by Django 2.1 on 2020-12-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('value', models.FloatField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'config',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
    ]
