# Generated by Django 4.1 on 2024-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20221105_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
