# Generated by Django 3.2.3 on 2022-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20220917_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prognosis_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='recurrence_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='survival_time',
            field=models.IntegerField(default=0),
        ),
    ]
