# Generated by Django 3.2.3 on 2022-09-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20220921_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, default='0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drinking',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='男', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoking',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='viral_infection',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default=False, max_length=16),
        ),
    ]
