# Generated by Django 3.2.3 on 2022-09-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('patient', '0005_auto_20220924_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
