# Generated by Django 3.2.3 on 2023-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20221011_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_card',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
