# Generated by Django 3.2.3 on 2022-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20230501_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='viral_result',
            field=models.CharField(blank=True,default='',null=True,max_length=256),
        ),
        migrations.AddField(
            model_name='patient',
            name='viral_focus',
            field=models.CharField(blank=True,default='',null=True,max_length=256),
        ),
    ]
