# Generated by Django 3.2.3 on 2023-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0008_auto_20230501_1519"),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE patient_patient
            ADD COLUMN create_time_timestamp integer GENERATED ALWAYS AS
            (EXTRACT(EPOCH FROM create_time AT TIME ZONE 'UTC')) STORED;
            ALTER TABLE patient_patient
            ADD COLUMN update_time_timestamp integer GENERATED ALWAYS AS
            (EXTRACT(EPOCH FROM create_time AT TIME ZONE 'UTC')) STORED;
        """),
    ]
