# Generated by Django 2.1 on 2020-10-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmembers',
            options={'get_latest_by': 'id', 'ordering': ['-id'], 'verbose_name': '项目成员表', 'verbose_name_plural': '项目成员表'},
        ),
        migrations.AlterModelTable(
            name='projectmembers',
            table='project_members',
        ),
    ]
