# Generated by Django 2.1 on 2020-11-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
    ]
