# Generated by Django 2.1 on 2020-10-27 18:32

import django.db.models.deletion
import django.utils.timezone
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('flow', '0001_initial'),
        ('project', '0002_auto_20201019_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'RUNNING'), (3, 'FINISHED'), (4, 'FAILURED')], default=1)),
                ('progress', models.SmallIntegerField(default=0)),
                ('result_path', models.CharField(max_length=120, null=True)),
                ('keep_bam', models.BooleanField(default=False)),
                ('env', django_mysql.models.JSONField(default=dict)),
                ('memory', models.BigIntegerField()),
                ('samples', django_mysql.models.JSONField(default=dict)),
                ('parameter', django_mysql.models.JSONField(default=dict)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Flow')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
    ]
