# Generated by Django 4.1 on 2022-09-05 20:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('flow', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'RUNNING'), (3, 'FINISHED'), (4, 'FAILURED'), (5, 'CANCELED')], default=1)),
                ('progress', models.SmallIntegerField(default=0)),
                ('pid', models.BigIntegerField(null=True)),
                ('is_merge', models.BooleanField(default=False)),
                ('result_path', models.TextField(null=True)),
                ('result_dir', models.CharField(max_length=120, null=True)),
                ('keep_bam', models.BooleanField(default=False)),
                ('has_cleaned', models.BooleanField(default=False)),
                ('is_qc', models.BooleanField(default=False)),
                ('env', models.JSONField()),
                ('priority', models.SmallIntegerField(default=1)),
                ('memory', models.BigIntegerField()),
                ('samples', models.JSONField()),
                ('parameter', models.JSONField(null=True)),
                ('error_message', models.TextField(default='', null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flow')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
    ]
