# Generated by Django 2.1 on 2020-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='result_dir',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
