# Generated by Django 2.1 on 2020-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201028_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'RUNNING'), (3, 'FINISHED'), (4, 'FAILURED'), (5, 'CANCELED')], default=1),
        ),
    ]
