# Generated by Django 3.2.3 on 2022-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
