# Generated by Django 3.2.3 on 2022-10-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log',
            field=models.TextField(null=True),
        ),
    ]
