# Generated by Django 3.2.3 on 2023-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_tempdir',
            field=models.BooleanField(default=False),
        ),
    ]
