# Generated by Django 2.1 on 2020-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20201115_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_qc',
            field=models.BooleanField(default=False),
        ),
    ]
