# Generated by Django 3.2.3 on 2023-04-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_tasksample'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_message_CN',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='error_message_EN',
            field=models.TextField(default='', null=True),
        ),
    ]
