# Generated by Django 2.1 on 2020-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_is_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
