# Generated by Django 3.2.3 on 2023-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20230411_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='result_path_CN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='result_path_EN',
            field=models.TextField(null=True),
        ),
    ]
