# Generated by Django 2.1 on 2020-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20201127_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_merge',
            field=models.BooleanField(default=False),
        ),
    ]
