# Generated by Django 2.1 on 2020-12-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_is_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result_path',
            field=models.TextField(null=True),
        ),
    ]
