# Generated by Django 2.1 on 2020-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20201207_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_message',
            field=models.TextField(default='', null=True),
        ),
    ]
