# Generated by Django 3.2.3 on 2022-08-29 20:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_task_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='env',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='parameter',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='samples',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
