PATIENT_ZH_TO_EN = {
    "患者识别号": "identifier",
    "送检机构": "inspection_agency",
    "年龄": "age",
    "诊疗医生": "medical_doctor",
    "性别": "gender",
    "姓名": "name",
    "出生日期": "birthday",
    "身份证": "id_card",
    "家庭地址": "location",
    "临床诊断": "diagnosis",
    "遗传病": "disease",
    "家族史": "family_history",
    "用药史": "medication_history",
    "治疗史": "treatment_history",
    "预后时间": "prognosis_time",
    "复发时间": "recurrence_time",
    "存活时间": "survival_time",
    "肿瘤分期": "tumor_stage",
}