-- 为task_sample表添加custom_name字段
ALTER TABLE task_sample ADD COLUMN custom_name VARCHAR(255);
-- 为task_sample表添加sampling_rate字段
ALTER TABLE task_sample ADD COLUMN sample_ratio DOUBLE PRECISION;

ALTER TABLE flow ADD COLUMN support_custom_sample_name BOOLEAN NOT NULL DEFAULT FALSE;
-- 为flow表添加support_sample_ratio字段
ALTER TABLE flow ADD COLUMN support_sample_ratio BOOLEAN NOT NULL DEFAULT FALSE;


create table reference_genome
(
    id  integer generated by default as identity primary key,
    custom_database     varchar(255)                           not null,
    virus_name          jsonb                    default '{}'::jsonb,
    virus_type          jsonb                    default '{}'::jsonb,
    host                varchar(255),
    host_genome_version varchar(255),
    host_seq_file       varchar(500),
    virus_seq_file      varchar(500),
    host_map_db         jsonb                    default '{}'::jsonb,
    sp_map_db           jsonb                    default '{}'::jsonb,
    create_time         timestamp with time zone default now() not null,
    update_time         timestamp with time zone default now() not null,
    is_deleted          boolean                  default false not null,
    status              varchar(50)              default 'RUNNING'::character varying,
    message             jsonb                    default '{}'::jsonb
);
comment on table reference_genome is '自建参考基因组表';
comment on column reference_genome.id is '主键ID';
comment on column reference_genome.custom_database is '自定义数据库名称';
comment on column reference_genome.virus_name is '病毒种名信息，JSON格式';
comment on column reference_genome.virus_type is '病毒分型信息，JSON格式';
comment on column reference_genome.host is '宿主信息';
comment on column reference_genome.host_genome_version is '宿主基因组版本信息';
comment on column reference_genome.host_seq_file is '宿主原序列文件路径';
comment on column reference_genome.virus_seq_file is '病原原序列文件路径';
comment on column reference_genome.host_map_db is '宿主原序列详细信息，JSON格式';
comment on column reference_genome.sp_map_db is '病原原序列详细信息，JSON格式';
comment on column reference_genome.create_time is '创建时间';
comment on column reference_genome.update_time is '修改时间';
comment on column reference_genome.is_deleted is '软删除标识，TRUE表示已删除';