# Generated by Django 2.1 on 2020-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='desp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
