# Generated by Django 4.1 on 2022-11-08 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('desp', models.TextField(blank=True, default='')),
                ('sort', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'panel_group',
                'ordering': ['sort', '-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('desp', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('panel_group', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='flow.panelgroup')),
            ],
            options={
                'db_table': 'panel',
                'ordering': ['sort', '-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='panel',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='flow.panel'),
        ),
    ]
