# Generated by Django 2.1 on 2020-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20201121_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_type',
            field=models.CharField(blank=True, default='normal', max_length=64),
        ),
    ]
