# Generated by Django 4.1 on 2024-09-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0002_panelgroup_panel_flow_panel"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="allow_define_report",
            field=models.BooleanField(default=False),
        ),
    ]
