# Generated by Django 2.1 on 2020-11-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_flow_flow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
