# Generated by Django 2.1 on 2020-11-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_flow_flow_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='sample_type',
            field=models.CharField(blank=True, default='multiple', max_length=64),
        ),
    ]
