# Generated by Django 2.1 on 2020-11-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_flow_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
