# Generated by Django 2.1 on 2020-11-30 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201127_1602'),
        ('flow', '0006_flow_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Flow')),
            ],
            options={
                'verbose_name': '流程的权限分配表',
                'verbose_name_plural': '流程的权限分配表',
                'db_table': 'flow_members',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='members',
            field=models.ManyToManyField(related_name='join_flows', through='flow.FlowMembers', to='account.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='flowmembers',
            unique_together={('account', 'flow')},
        ),
    ]
