# Generated by Django 2.1 on 2020-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_auto_20201130_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='allow_nonstandard_samples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flow',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
