# Generated by Django 2.1 on 2020-12-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_flow2sample'),
        ('flow', '0008_auto_20201201_1449'),
    ]

    operations = [
    ]
