# Generated by Django 2.1 on 2020-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0009_merge_20201204_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow2sample',
            options={'get_latest_by': 'id', 'ordering': ['-id'], 'verbose_name': '流程样本表', 'verbose_name_plural': '流程样本表'},
        ),
        migrations.AddField(
            model_name='flow2sample',
            name='project_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='flow2sample',
            table='flow_samples',
        ),
    ]
