# Generated by Django 2.1 on 2020-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_auto_20201205_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='memory',
            field=models.BigIntegerField(default=1024),
        ),
    ]
